---
title: "Data Analysis"
author: "Author"
date: '`r Sys.Date()`'
output:
  md_document: 
    variant: markdown_github
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='FigSpatial/',
                      echo=T, warning=FALSE, message=T)
```

```{r}
setwd("~/git/subgraph/mgc_based/")

require('igraph')
require('ggplot2')
require('fields')

options(max.print=100)

listGs<- list.files(path = "../graphml/", pattern = "*.graphml")

#read in covariates and graph list
#find those with common ids, sort by id

covariates<- read.csv("../covariates/predictors.csv",stringsAsFactors = F)
ids <- unlist( lapply(listGs,function(x)strtrim(x,6)))
common_id<- intersect(covariates$RUNNO , ids)

covariates <- covariates[covariates$RUNNO%in%common_id,]
covariates <- covariates[order(covariates$RUNNO),]  

listGs<- listGs[ids%in%common_id]
listGs<- listGs[order(listGs)]

graphList<- lapply(listGs, function(x){
  read.graph( file = paste("../graphml/",x,sep = ""),format = "graphml")
})

AdjacencyList<- lapply(graphList, function(x){
  get.adjacency(x)
})


n = nrow(AdjacencyList[[1]])
half = c(1:(n/2))
reordered = c( half*2-1,half*2)

TriangleList <-  lapply(graphList, function(x){
  a=count_triangles(x)
  a[reordered]
})


CluscoeffList<- lapply(graphList, function(x){
  a=transitivity(x,"local")
  a[reordered]
})

AdjacencyList<- lapply(AdjacencyList, function(x){
  x[reordered,reordered]
})

HemisphereList<- lapply(graphList, function(x){
  get.vertex.attribute(x,name="hemisphere")
})

DegreeList<- lapply(AdjacencyList, function(x){
  rowSums(as.matrix(x))
  })

####

AdjacencyListPick =  list()
TriangleListPick =list()
CluscoeffListPick = list()
for(i in 1:length(AdjacencyList)){
  if(covariates$GENOTYPE[i]>=1){
    AdjacencyListPick[[length(AdjacencyListPick)+1]] = AdjacencyList[[i]]
    TriangleListPick[[length(TriangleListPick)+1]] = TriangleList[[i]]
    CluscoeffListPick[[length(CluscoeffListPick)+1]] = CluscoeffList[[i]]
  }
}


DegreeListPick<- lapply(AdjacencyListPick, function(x){
  rowSums(as.matrix(x))
  })



GENOTYPEPick = covariates$GENOTYPE[covariates$GENOTYPE>=1]

SEXPick = covariates$GENDER[covariates$GENOTYPE>=1]

m = length(GENOTYPEPick)
```

```{r}

load(file="cov_embedding.RDa")
```


```{r}

C = sapply(c(1:m),function(x)diag(testObj$C[,,x]))
plot(t(C[1:2,]),col=GENOTYPEPick)
plot(t(C[1:3,]),col=GENOTYPEPick)

library(plotly)

plotly_C = data.frame(t(C))
colnames(plotly_C)<- c("x","y","z")

p <- plot_ly(plotly_C, x = ~x, y = ~y, z = ~z, color = ~as.factor(GENOTYPEPick), colors = c('#BF382A', '#0C4B8E')) %>%
  add_markers() %>%
  layout(scene = list(xaxis = list(title = 'x'),
                      yaxis = list(title = 'y'),
                      zaxis = list(title = 'z')))

p

```
```{r}

require("MASS")

geno_fit = lda(plotly_C, GENOTYPEPick)
geno_fit
geno_error = sum(predict(geno_fit)$class != GENOTYPEPick) / m
geno_error
```

```{r}

p <- plot_ly(plotly_C, x = ~x, y = ~y, z = ~z, color = ~as.factor(SEXPick), colors = c('#BF382A', '#0C4B8E')) %>%
  add_markers() %>%
  layout(scene = list(xaxis = list(title = 'x'),
                      yaxis = list(title = 'y'),
                      zaxis = list(title = 'z')))

p

```

```{r}

require("MASS")

geno_fit = lda(plotly_C, SEXPick)
geno_fit
geno_error = sum(predict(geno_fit)$class != GENOTYPEPick) / m
geno_error
```
